command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: user
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ include "keycloak.fullname" . }}-admin-creds
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.awt.headless=true
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  - name: KC_HOSTNAME
    value: keycloak-ci

database:
  vendor: dev-file

secrets:
  admin-creds:
    annotations:
      my-test-annotation: Test secret for {{ include "keycloak.fullname" . }}
    stringData:
      user: admin
      password: secret

http:
  relativePath: "/"

test:
  enabled: true

livenessProbe: |
  httpGet:
    path: '/health/live'
    port: 8080
  initialDelaySeconds: 0
  timeoutSeconds: 5

readinessProbe: |
  httpGet:
    path: '/health/ready'
    port: 8080
  initialDelaySeconds: 10
  timeoutSeconds: 1

startupProbe: |
  httpGet:
    path: '/health'
    port: 8080
  initialDelaySeconds: 15
  timeoutSeconds: 1
  failureThreshold: 60
  periodSeconds: 5
